version: "3.9"

services:
  api_zrp:
    container_name: api_zrp
    image: api_zrp:1.0
    network_mode: host
    build:
      context: .
    environment:
      - FLASK_ENV=Development
      - FLASK_DEBUG=True
      - FLASK_APP=./api_ZRP/app.py
      - FLASK_RUN_PORT=8000
      - URL_POKEMON=https://pokeapi.co/api/v2/pokemon/
